//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iChronoMe {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal localize() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iChronoMe.Core.localize.localize", typeof(localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save and quit ähnelt.
        /// </summary>
        public static string action_SaveAndQuit {
            get {
                return ResourceManager.GetString("action_SaveAndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die style ähnelt.
        /// </summary>
        public static string ActionButtonStyle {
            get {
                return ResourceManager.GetString("ActionButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die iChronEye animated
        ///(doubleclick = action) ähnelt.
        /// </summary>
        public static string ActionButtonStyle_eye_animated {
            get {
                return ResourceManager.GetString("ActionButtonStyle_eye_animated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die iChronEye static ähnelt.
        /// </summary>
        public static string ActionButtonStyle_eye_static {
            get {
                return ResourceManager.GetString("ActionButtonStyle_eye_static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die animation duriation ähnelt.
        /// </summary>
        public static string AnimationDuriation {
            get {
                return ResourceManager.GetString("AnimationDuriation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die animation rounds ähnelt.
        /// </summary>
        public static string AnimationRounds {
            get {
                return ResourceManager.GetString("AnimationRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die iChronoMe ähnelt.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die event name ähnelt.
        /// </summary>
        public static string AppointmentName {
            get {
                return ResourceManager.GetString("AppointmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die events ähnelt.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die event symbols ähnelt.
        /// </summary>
        public static string AppointmentSymbols {
            get {
                return ResourceManager.GetString("AppointmentSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die event time ähnelt.
        /// </summary>
        public static string AppointmentTime {
            get {
                return ResourceManager.GetString("AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die iChronoMe ähnelt.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die one rainbow per month ähnelt.
        /// </summary>
        public static string aRainbowPerMonth {
            get {
                return ResourceManager.GetString("aRainbowPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die one rainbow per year ähnelt.
        /// </summary>
        public static string aRainbowPerYear {
            get {
                return ResourceManager.GetString("aRainbowPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die background ähnelt.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die background color ähnelt.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die background image ähnelt.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die border ähnelt.
        /// </summary>
        public static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header colors ähnelt.
        /// </summary>
        public static string ButtonColor {
            get {
                return ResourceManager.GetString("ButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die calendar model ähnelt.
        /// </summary>
        public static string CalendarModel {
            get {
                return ResourceManager.GetString("CalendarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die calendar type ähnelt.
        /// </summary>
        public static string CalendarType {
            get {
                return ResourceManager.GetString("CalendarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die action on click ähnelt.
        /// </summary>
        public static string ClickAction {
            get {
                return ResourceManager.GetString("ClickAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die clock face ähnelt.
        /// </summary>
        public static string ClockFace {
            get {
                return ResourceManager.GetString("ClockFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hand colors ähnelt.
        /// </summary>
        public static string ClockHandColors {
            get {
                return ResourceManager.GetString("ClockHandColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die color ähnelt.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die black ähnelt.
        /// </summary>
        public static string colorcfgBlack {
            get {
                return ResourceManager.GetString("colorcfgBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die black/custom ähnelt.
        /// </summary>
        public static string colorcfgBlackCustom {
            get {
                return ResourceManager.GetString("colorcfgBlackCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die black/transparent ähnelt.
        /// </summary>
        public static string colorcfgBlackTransparent {
            get {
                return ResourceManager.GetString("colorcfgBlackTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die black/white ähnelt.
        /// </summary>
        public static string colorcfgBlackWhite {
            get {
                return ResourceManager.GetString("colorcfgBlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die multicolor ähnelt.
        /// </summary>
        public static string colorcfgMultiColor {
            get {
                return ResourceManager.GetString("colorcfgMultiColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die multicolor filled ähnelt.
        /// </summary>
        public static string colorcfgMultiColorFilled {
            get {
                return ResourceManager.GetString("colorcfgMultiColorFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die single color ähnelt.
        /// </summary>
        public static string colorcfgSingleColor {
            get {
                return ResourceManager.GetString("colorcfgSingleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die single color filled ähnelt.
        /// </summary>
        public static string colorcfgSingleColorFilled {
            get {
                return ResourceManager.GetString("colorcfgSingleColorFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die white ähnelt.
        /// </summary>
        public static string colorcfgWhite {
            get {
                return ResourceManager.GetString("colorcfgWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die white / black ähnelt.
        /// </summary>
        public static string colorcfgWhiteBlack {
            get {
                return ResourceManager.GetString("colorcfgWhiteBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die white / custom ähnelt.
        /// </summary>
        public static string colorcfgWhiteCurstom {
            get {
                return ResourceManager.GetString("colorcfgWhiteCurstom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die white / transparent ähnelt.
        /// </summary>
        public static string colorcfgWhiteTransparent {
            get {
                return ResourceManager.GetString("colorcfgWhiteTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die colors ähnelt.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die content and colors ähnelt.
        /// </summary>
        public static string ContentAnColors {
            get {
                return ResourceManager.GetString("ContentAnColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die content ähnelt.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die current ähnelt.
        /// </summary>
        public static string current {
            get {
                return ResourceManager.GetString("current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die current location ähnelt.
        /// </summary>
        public static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dark to light ähnelt.
        /// </summary>
        public static string DarkToLight {
            get {
                return ResourceManager.GetString("DarkToLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unable to interprete data-list ähnelt.
        /// </summary>
        public static string DataLoader_error_list_broken {
            get {
                return ResourceManager.GetString("DataLoader_error_list_broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unable to load data-list ähnelt.
        /// </summary>
        public static string DataLoader_error_list_unloadable {
            get {
                return ResourceManager.GetString("DataLoader_error_list_unloadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die day colors ähnelt.
        /// </summary>
        public static string DayColors {
            get {
                return ResourceManager.GetString("DayColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die brush timespan ähnelt.
        /// </summary>
        public static string DayColorsTimeSpan {
            get {
                return ResourceManager.GetString("DayColorsTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die day-color type ähnelt.
        /// </summary>
        public static string DayColorType {
            get {
                return ResourceManager.GetString("DayColorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die there will popup color selectors
        ///each selected color will be added to the brush
        ///if you have enoug colors just click &apos;back&apos; or somewhere outside the window ähnelt.
        /// </summary>
        public static string DayColorTypeCustomInfo {
            get {
                return ResourceManager.GetString("DayColorTypeCustomInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tagestitel ähnelt.
        /// </summary>
        public static string DayTitle {
            get {
                return ResourceManager.GetString("DayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die default ähnelt.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deleted widges ähnelt.
        /// </summary>
        public static string DeletedWidgets {
            get {
                return ResourceManager.GetString("DeletedWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die discription ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die solar time needs a location! ähnelt.
        /// </summary>
        public static string error_SloarTimeNeedLocation {
            get {
                return ResourceManager.GetString("error_SloarTimeNeedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die errors or problems ähnelt.
        /// </summary>
        public static string ErrorsOrProblems {
            get {
                return ResourceManager.GetString("ErrorsOrProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fill ähnelt.
        /// </summary>
        public static string Filling {
            get {
                return ResourceManager.GetString("Filling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die five colors ähnelt.
        /// </summary>
        public static string fiveColors {
            get {
                return ResourceManager.GetString("fiveColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die flow ähnelt.
        /// </summary>
        public static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die four colors ähnelt.
        /// </summary>
        public static string fourColors {
            get {
                return ResourceManager.GetString("fourColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Funktionen im Titel ähnelt.
        /// </summary>
        public static string FunctionInTitle {
            get {
                return ResourceManager.GetString("FunctionInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hand colors ähnelt.
        /// </summary>
        public static string HandColors {
            get {
                return ResourceManager.GetString("HandColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hand color types ähnelt.
        /// </summary>
        public static string HandColorTypes {
            get {
                return ResourceManager.GetString("HandColorTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hand types ähnelt.
        /// </summary>
        public static string HandTypes {
            get {
                return ResourceManager.GetString("HandTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die button color ähnelt.
        /// </summary>
        public static string HeaderColor {
            get {
                return ResourceManager.GetString("HeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hour hand fill color ähnelt.
        /// </summary>
        public static string HourHandFill {
            get {
                return ResourceManager.GetString("HourHandFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hour hand stroke color ähnelt.
        /// </summary>
        public static string HourHandStroke {
            get {
                return ResourceManager.GetString("HourHandStroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hours ähnelt.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die icon color ähnelt.
        /// </summary>
        public static string IconColor {
            get {
                return ResourceManager.GetString("IconColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unable to interprete image-list ähnelt.
        /// </summary>
        public static string ImageLoader_error_list_broken {
            get {
                return ResourceManager.GetString("ImageLoader_error_list_broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unable to load image-list ähnelt.
        /// </summary>
        public static string ImageLoader_error_list_unloadable {
            get {
                return ResourceManager.GetString("ImageLoader_error_list_unloadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading {0} images... ähnelt.
        /// </summary>
        public static string ImageLoader_progress_n_images {
            get {
                return ResourceManager.GetString("ImageLoader_progress_n_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading {0} packages... ähnelt.
        /// </summary>
        public static string ImageLoader_progress_n_packages {
            get {
                return ResourceManager.GetString("ImageLoader_progress_n_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading one image... ähnelt.
        /// </summary>
        public static string ImageLoader_progress_one_image {
            get {
                return ResourceManager.GetString("ImageLoader_progress_one_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading one package... ähnelt.
        /// </summary>
        public static string ImageLoader_progress_one_package {
            get {
                return ResourceManager.GetString("ImageLoader_progress_one_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die updating preview-images... ähnelt.
        /// </summary>
        public static string ImageLoader_progress_title {
            get {
                return ResourceManager.GetString("ImageLoader_progress_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} images loadet... ähnelt.
        /// </summary>
        public static string ImageLoader_success_n_images {
            get {
                return ResourceManager.GetString("ImageLoader_success_n_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} packages loadet... ähnelt.
        /// </summary>
        public static string ImageLoader_success_n_packages {
            get {
                return ResourceManager.GetString("ImageLoader_success_n_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die one image loadet... ähnelt.
        /// </summary>
        public static string ImageLoader_success_one_image {
            get {
                return ResourceManager.GetString("ImageLoader_success_one_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die one package loadet... ähnelt.
        /// </summary>
        public static string ImageLoader_success_one_package {
            get {
                return ResourceManager.GetString("ImageLoader_success_one_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die live-time ähnelt.
        /// </summary>
        public static string LifeTime {
            get {
                return ResourceManager.GetString("LifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die live-start ähnelt.
        /// </summary>
        public static string LifeTimeStart {
            get {
                return ResourceManager.GetString("LifeTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die light to dark ähnelt.
        /// </summary>
        public static string LightToDark {
            get {
                return ResourceManager.GetString("LightToDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die lines ähnelt.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die location ähnelt.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die location type ähnelt.
        /// </summary>
        public static string LocationType {
            get {
                return ResourceManager.GetString("LocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die max count ähnelt.
        /// </summary>
        public static string MaxCount {
            get {
                return ResourceManager.GetString("MaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minute hand fill color ähnelt.
        /// </summary>
        public static string MinuteHandFill {
            get {
                return ResourceManager.GetString("MinuteHandFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minute hand stroke color ähnelt.
        /// </summary>
        public static string MinuteHandStroke {
            get {
                return ResourceManager.GetString("MinuteHandStroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes ähnelt.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die months ähnelt.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die more options and colors ähnelt.
        /// </summary>
        public static string MoreOptionsAndColors {
            get {
                return ResourceManager.GetString("MoreOptionsAndColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} round(s) ähnelt.
        /// </summary>
        public static string nAnimationRounds {
            get {
                return ResourceManager.GetString("nAnimationRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no highlite ähnelt.
        /// </summary>
        public static string NoHighlite {
            get {
                return ResourceManager.GetString("NoHighlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} second(s) ähnelt.
        /// </summary>
        public static string nSeconds {
            get {
                return ResourceManager.GetString("nSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on click ähnelt.
        /// </summary>
        public static string OnClick {
            get {
                return ResourceManager.GetString("OnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die one Month ähnelt.
        /// </summary>
        public static string oneMonth {
            get {
                return ResourceManager.GetString("oneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die one Year ähnelt.
        /// </summary>
        public static string oneYear {
            get {
                return ResourceManager.GetString("oneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die options ähnelt.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die additional ähnelt.
        /// </summary>
        public static string OtherAdditional {
            get {
                return ResourceManager.GetString("OtherAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die per month ähnelt.
        /// </summary>
        public static string perMonth {
            get {
                return ResourceManager.GetString("perMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die per week ähnelt.
        /// </summary>
        public static string perWeek {
            get {
                return ResourceManager.GetString("perWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die per year ähnelt.
        /// </summary>
        public static string perYear {
            get {
                return ResourceManager.GetString("perYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die problems ähnelt.
        /// </summary>
        public static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die update base-data ähnelt.
        /// </summary>
        public static string ProgressUpdateBaseData {
            get {
                return ResourceManager.GetString("ProgressUpdateBaseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sample ähnelt.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save widget ähnelt.
        /// </summary>
        public static string SaveWidget {
            get {
                return ResourceManager.GetString("SaveWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die second hand fill color ähnelt.
        /// </summary>
        public static string SecondHandFill {
            get {
                return ResourceManager.GetString("SecondHandFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die second hand stroke color ähnelt.
        /// </summary>
        public static string SecondHandStroke {
            get {
                return ResourceManager.GetString("SecondHandStroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die this app was created be me, the creator. I call myself &apos;I&apos;. ähnelt.
        /// </summary>
        public static string serviceAboutIntor {
            get {
                return ResourceManager.GetString("serviceAboutIntor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die all colors at ones ähnelt.
        /// </summary>
        public static string SetAllColorsAtOnce {
            get {
                return ResourceManager.GetString("SetAllColorsAtOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show all calendars ähnelt.
        /// </summary>
        public static string ShowAllCalendars {
            get {
                return ResourceManager.GetString("ShowAllCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show event-colors ähnelt.
        /// </summary>
        public static string ShowAppointmentColors {
            get {
                return ResourceManager.GetString("ShowAppointmentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show location ähnelt.
        /// </summary>
        public static string ShowLocation {
            get {
                return ResourceManager.GetString("ShowLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die single color ähnelt.
        /// </summary>
        public static string SingleColor {
            get {
                return ResourceManager.GetString("SingleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die choose static location ähnelt.
        /// </summary>
        public static string StaticLocation {
            get {
                return ResourceManager.GetString("StaticLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die style ähnelt.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Symbole ähnelt.
        /// </summary>
        public static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfarbe ähnelt.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die theme ähnelt.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die three Colors ähnelt.
        /// </summary>
        public static string threeColors {
            get {
                return ResourceManager.GetString("threeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die three Months ähnelt.
        /// </summary>
        public static string threeMonths {
            get {
                return ResourceManager.GetString("threeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die three Weeks ähnelt.
        /// </summary>
        public static string threeWeeks {
            get {
                return ResourceManager.GetString("threeWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tick marks ähnelt.
        /// </summary>
        public static string TickMarks {
            get {
                return ResourceManager.GetString("TickMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tick marks color ähnelt.
        /// </summary>
        public static string TickMarksColor {
            get {
                return ResourceManager.GetString("TickMarksColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die time ähnelt.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die time offset ähnelt.
        /// </summary>
        public static string TimeOffset {
            get {
                return ResourceManager.GetString("TimeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die timescale ähnelt.
        /// </summary>
        public static string TimeScale {
            get {
                return ResourceManager.GetString("TimeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die timespan ähnelt.
        /// </summary>
        public static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die time-type ähnelt.
        /// </summary>
        public static string TimeType {
            get {
                return ResourceManager.GetString("TimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit Widget ähnelt.
        /// </summary>
        public static string title_EditWidget {
            get {
                return ResourceManager.GetString("title_EditWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die title color ähnelt.
        /// </summary>
        public static string TitleColor {
            get {
                return ResourceManager.GetString("TitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die today-color ähnelt.
        /// </summary>
        public static string TodayColor {
            get {
                return ResourceManager.GetString("TodayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die transparent ähnelt.
        /// </summary>
        public static string transparent {
            get {
                return ResourceManager.GetString("transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die two Colors ähnelt.
        /// </summary>
        public static string twoColors {
            get {
                return ResourceManager.GetString("twoColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die two Months ähnelt.
        /// </summary>
        public static string twoMonths {
            get {
                return ResourceManager.GetString("twoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die two Weeks ähnelt.
        /// </summary>
        public static string twoWeeks {
            get {
                return ResourceManager.GetString("twoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Widget-Kopf und Trennzeile ähnelt.
        /// </summary>
        public static string WidgetHeaderAndSeparatingLine {
            get {
                return ResourceManager.GetString("WidgetHeaderAndSeparatingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Widget-Titel ähnelt.
        /// </summary>
        public static string WidgetTitle {
            get {
                return ResourceManager.GetString("WidgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die agenda ähnelt.
        /// </summary>
        public static string WidgetTitleAgenda {
            get {
                return ResourceManager.GetString("WidgetTitleAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die circle-wave ähnelt.
        /// </summary>
        public static string WidgetTitleCircleWave {
            get {
                return ResourceManager.GetString("WidgetTitleCircleWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die month-view ähnelt.
        /// </summary>
        public static string WidgetTitleMonthView {
            get {
                return ResourceManager.GetString("WidgetTitleMonthView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die without second-hand ähnelt.
        /// </summary>
        public static string withoutSecondHand {
            get {
                return ResourceManager.GetString("withoutSecondHand", resourceCulture);
            }
        }
    }
}
