//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iChronoMe.Core.ml {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iChronoMe.Core.ml.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die iChronoMe ähnelt.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termin-Name ähnelt.
        /// </summary>
        internal static string AppointmentName {
            get {
                return ResourceManager.GetString("AppointmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termine ähnelt.
        /// </summary>
        internal static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termin-Symbole ähnelt.
        /// </summary>
        internal static string AppointmentSymbols {
            get {
                return ResourceManager.GetString("AppointmentSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termin-Zeit ähnelt.
        /// </summary>
        internal static string AppointmentTime {
            get {
                return ResourceManager.GetString("AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die iChronoMe ähnelt.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hintergrund ähnelt.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hintergrundfarbe ähnelt.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rahmen ähnelt.
        /// </summary>
        internal static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knopffarben ähnelt.
        /// </summary>
        internal static string ButtonColor {
            get {
                return ResourceManager.GetString("ButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kalendermodell ähnelt.
        /// </summary>
        internal static string CalendarModel {
            get {
                return ResourceManager.GetString("CalendarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe ähnelt.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farben ähnelt.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content and Colors ähnelt.
        /// </summary>
        internal static string ContentAnColors {
            get {
                return ResourceManager.GetString("ContentAnColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inhalte ähnelt.
        /// </summary>
        internal static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tagestitel ähnelt.
        /// </summary>
        internal static string DayTitle {
            get {
                return ResourceManager.GetString("DayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler oder Probleme ähnelt.
        /// </summary>
        internal static string ErrorsOrProblems {
            get {
                return ResourceManager.GetString("ErrorsOrProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Füllung ähnelt.
        /// </summary>
        internal static string Filling {
            get {
                return ResourceManager.GetString("Filling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die flow ähnelt.
        /// </summary>
        internal static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Funktionen im Titel ähnelt.
        /// </summary>
        internal static string FunctionInTitle {
            get {
                return ResourceManager.GetString("FunctionInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knopffarbe ähnelt.
        /// </summary>
        internal static string HeaderColor {
            get {
                return ResourceManager.GetString("HeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stunden ähnelt.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unable to interprete image-list ähnelt.
        /// </summary>
        internal static string ImageLoader_error_list_broken {
            get {
                return ResourceManager.GetString("ImageLoader_error_list_broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unable to load image-list ähnelt.
        /// </summary>
        internal static string ImageLoader_error_list_unloadable {
            get {
                return ResourceManager.GetString("ImageLoader_error_list_unloadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading {0} images... ähnelt.
        /// </summary>
        internal static string ImageLoader_progress_n_images {
            get {
                return ResourceManager.GetString("ImageLoader_progress_n_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading one image... ähnelt.
        /// </summary>
        internal static string ImageLoader_progress_one_image {
            get {
                return ResourceManager.GetString("ImageLoader_progress_one_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die updating preview-images... ähnelt.
        /// </summary>
        internal static string ImageLoader_progress_title {
            get {
                return ResourceManager.GetString("ImageLoader_progress_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} images loadet... ähnelt.
        /// </summary>
        internal static string ImageLoader_success_n_images {
            get {
                return ResourceManager.GetString("ImageLoader_success_n_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die one image loadet... ähnelt.
        /// </summary>
        internal static string ImageLoader_success_one_image {
            get {
                return ResourceManager.GetString("ImageLoader_success_one_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lebenszeit ähnelt.
        /// </summary>
        internal static string LifeTime {
            get {
                return ResourceManager.GetString("LifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lebensstart ähnelt.
        /// </summary>
        internal static string LifeTimeStart {
            get {
                return ResourceManager.GetString("LifeTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeilen ähnelt.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximale Anzahl ähnelt.
        /// </summary>
        internal static string MaxCount {
            get {
                return ResourceManager.GetString("MaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minuten ähnelt.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on click ähnelt.
        /// </summary>
        internal static string OnClick {
            get {
                return ResourceManager.GetString("OnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optionen ähnelt.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiteres ähnelt.
        /// </summary>
        internal static string OtherAdditional {
            get {
                return ResourceManager.GetString("OtherAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Probleme ähnelt.
        /// </summary>
        internal static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Widget speichern ähnelt.
        /// </summary>
        internal static string SaveWidget {
            get {
                return ResourceManager.GetString("SaveWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sekunden ähnelt.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Farben auf einmal ähnelt.
        /// </summary>
        internal static string SetAllColorsAtOnce {
            get {
                return ResourceManager.GetString("SetAllColorsAtOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Kalender anzeigen ähnelt.
        /// </summary>
        internal static string ShowAllCalendars {
            get {
                return ResourceManager.GetString("ShowAllCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminfarben anzeigen ähnelt.
        /// </summary>
        internal static string ShowAppointmentColors {
            get {
                return ResourceManager.GetString("ShowAppointmentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ort anzeigen ähnelt.
        /// </summary>
        internal static string ShowLocation {
            get {
                return ResourceManager.GetString("ShowLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Symbole ähnelt.
        /// </summary>
        internal static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfarbe ähnelt.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skala ähnelt.
        /// </summary>
        internal static string TickMarks {
            get {
                return ResourceManager.GetString("TickMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skala-Farbe ähnelt.
        /// </summary>
        internal static string TickMarksColor {
            get {
                return ResourceManager.GetString("TickMarksColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeit ähnelt.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitunterschied ähnelt.
        /// </summary>
        internal static string TimeOffset {
            get {
                return ResourceManager.GetString("TimeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitraum ähnelt.
        /// </summary>
        internal static string TimeScale {
            get {
                return ResourceManager.GetString("TimeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeit-Typ ähnelt.
        /// </summary>
        internal static string TimeType {
            get {
                return ResourceManager.GetString("TimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titelfarbe ähnelt.
        /// </summary>
        internal static string TitleColor {
            get {
                return ResourceManager.GetString("TitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Widget-Kopf und Trennzeile ähnelt.
        /// </summary>
        internal static string WidgetHeaderAndSeparatingLine {
            get {
                return ResourceManager.GetString("WidgetHeaderAndSeparatingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Widget-Titel ähnelt.
        /// </summary>
        internal static string WidgetTitle {
            get {
                return ResourceManager.GetString("WidgetTitle", resourceCulture);
            }
        }
    }
}
